
language: cpp

os: linux
dist: trusty
sudo: false
compiler: gcc

addons:
  apt:
    packages:
      - libboost-dev
      - libboost-test-dev

script:
  - ./autogen.sh
  - ./configure --disable-static --enable-unity-build CXXFLAGS='-O2'
  - make -j 2
  - ./test-suite/quantlib-test-suite --log_level=message -- --faster

