
language: cpp

os: linux
dist: trusty
sudo: false
compiler: gcc

cache: ccache

addons:
  apt:
    packages:
      - libboost-dev
      - libboost-test-dev

script:
  - ./autogen.sh
  - ./configure --disable-static
  - ccache --zero-stats
  - ccache --max-size=2G
  - make -j 2
  - ccache --show-stats

