
language: cpp

os: linux
dist: trusty
sudo: required
compiler: gcc
services: docker

cache: ccache

before_install:
  - docker pull lballabio/boost

script:
  - ./autogen.sh
  - docker run --rm -ti -v ${HOME}/.ccache:/root/.ccache -v ${TRAVIS_BUILD_DIR}:/build -w /build lballabio/boost ./configure --disable-static CXXFLAGS='-O2'
  - docker run --rm -ti -v ${HOME}/.ccache:/root/.ccache -v ${TRAVIS_BUILD_DIR}:/build -w /build lballabio/boost ccache --zero-stats
  - docker run --rm -ti -v ${HOME}/.ccache:/root/.ccache -v ${TRAVIS_BUILD_DIR}:/build -w /build lballabio/boost ccache --max-size=2.5G
  - docker run --rm -ti -v ${HOME}/.ccache:/root/.ccache -v ${TRAVIS_BUILD_DIR}:/build -w /build lballabio/boost make -j 2
  - docker run --rm -ti -v ${HOME}/.ccache:/root/.ccache -v ${TRAVIS_BUILD_DIR}:/build -w /build lballabio/boost ccache --show-stats
  - docker run --rm -ti -v ${HOME}/.ccache:/root/.ccache -v ${TRAVIS_BUILD_DIR}:/build -w /build lballabio/boost ./test-suite/quantlib-test-suite --log_level=message -- --faster

